export { default as HomePage } from "./Home"
export { default as ProductsPage } from "./Products"
export { default as OrdersPage } from "./Orders"
export { default as LoginPage } from "./Login"
export { default as ContactUsPage } from "./ContactUs"
